import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CdkTreeModule } from '@angular/cdk/tree';
import {
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatButtonModule,
    MatCardModule,
    MatTooltipModule,
    MatSelectModule,
    MatSortModule,
    MatIconModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatCheckboxModule,
    MatRadioModule,
    MatProgressBarModule,
    MatSnackBarModule,
    MatTreeModule,
    MatBottomSheetModule,
    MatTabsModule,
    MatPaginatorModule,
    MatTableModule,
    MatFormFieldModule,
    MatAutocompleteModule,
    MatToolbarModule,
    MatSidenavModule,
    MatMenuModule,
    MatChipsModule,
    MatExpansionModule,
    MatStepperModule,
  } from '@angular/material';

@NgModule({
    exports: [
        MatDatepickerModule,
        MatNativeDateModule,
        MatButtonModule,
        MatInputModule,
        MatCardModule,
        MatTooltipModule,
        MatSelectModule,
        MatSortModule,
        MatIconModule,
        MatListModule,
        MatProgressSpinnerModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatCheckboxModule,
        MatRadioModule,
        MatProgressBarModule,
        MatSnackBarModule,
        MatTreeModule,
        MatBottomSheetModule,
        MatTabsModule,
        MatPaginatorModule,
        MatTableModule,
        MatFormFieldModule,
        MatAutocompleteModule,
        MatToolbarModule,
        MatSidenavModule,
        MatMenuModule,
        MatChipsModule,
        MatExpansionModule,
        MatStepperModule,
    ]
})

export class MaterialModule { }
